[versions]
agp = "8.7.3"
kotlin = "2.0.21"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.2"
constraintlayout = "2.2.0"
junit = "4.13.2"
junit-ext = "1.2.1"
espresso-core = "3.6.1"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
extJunit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-ext" }
espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

[bundles]

[metadata]
generated = true
